---
assert_lefthook_installed: true
skip_lfs: true

commit-msg:
  commands:
    "lint commit message":
      run: commitlint --edit {1}

pre-commit:
  parallel: true
  jobs:
    - name: format yaml
      glob: "*.yaml"
      run: yamlfmt {staged_files}
      tags:
        - format
      stage_fixed: true

    - name: format markdown
      glob: "*.md"
      run: prettier --write {staged_files}
      tags:
        - docs
      stage_fixed: true

    - name: format just
      glob:
        - "*.just"
        - ".justfile"
      run: |
        for file in {staged_files}; do
          just --justfile "$file" --fmt --unstable
        done
      tags:
        - format
      stage_fixed: true
