apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-new
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi   # >= current
  storageClassName: ceph-rbd   # operator SC (ceph-proxmox)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-new
  namespace: media
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
  storageClassName: ceph-rbd
