---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  namespaceSelector:
    matchNames:
      - jellyfin
  endpoints:
    - port: http           # must be the Service port’s name, not the number
      scheme: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s

