komga:
  baseUri: "${KOMF_KOMGA_BASE_URI}"
  komgaUser: "${KOMF_KOMGA_USER}"
  komgaPassword: "${KOMF_KOMGA_PASSWORD}"

  eventListener:
    enabled: true
    metadataLibraryFilter: []
    metadataSeriesExcludeFilter: []
    notificationsLibraryFilter: []

  metadataUpdate:
    default:
      libraryType: "MANGA"
      updateModes: [API]
      aggregate: false
      mergeTags: false
      mergeGenres: false
      bookCovers: true
      seriesCovers: true
      overrideExistingCovers: true
      overrideComicInfo: false
      postProcessing:
        seriesTitle: true
        seriesTitleLanguage: "en"
        fallbackToAltTitle: false
        alternativeSeriesTitles: false
        alternativeSeriesTitleLanguages:
          - "en"
          - "ja"
          - "ja-ro"
        orderBooks: true
        scoreTagName: "score"
        readingDirectionValue:
        languageValue:
        originalPublisherTagName:

database:
  file: /config/database.sqlite

metadataProviders:
  malClientId: "${KOMF_METADATA_PROVIDERS_MAL_CLIENT_ID}"
  comicVineApiKey: "${KOMF_METADATA_PROVIDERS_COMIC_VINE_API_KEY}"
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: "MANGA"
      authorRoles: ["WRITER"]
      artistRoles: ["PENCILLER", "INKER", "COLORIST", "LETTERER", "COVER"]

    mal:
      priority: 20
      enabled: true
      mediaType: "MANGA"

    aniList:
      priority: 40
      enabled: false
      mediaType: "MANGA"
      tagsScoreThreshold: 60
      tagsSizeLimit: 15

    mangaDex:
      priority: 90
      enabled: true
      coverLanguages:
        - "en"
        - "ja"

    comicVine:
      priority: 110
      enabled: false

server:
  port: 8085

logLevel: INFO
