komga:
  baseUri: "${KOMF_KOMGA_BASE_URI}"
  komgaUser: "${KOMF_KOMGA_USER}"
  komgaPassword: "${KOMF_KOMGA_PASSWORD}"

  eventListener:
    enabled: true
    metadataLibraryFilter: []
    metadataSeriesExcludeFilter: []
    notificationsLibraryFilter: []

  metadataUpdate:
    default:
      updateModes: [API]
      aggregate: true
      mergeTags: true
      mergeGenres: true
      bookCovers: true
      seriesCovers: true
      postProcessing:
        seriesTitle: true
        seriesTitleLanguage: "en"
        alternativeSeriesTitles: false
        alternativeSeriesTitleLanguages:
          - "en"
          - "ja"
          - "ja-ro"
        orderBooks: true
        scoreTagName: "score"
        readingDirectionValue:
        languageValue:

database:
  file: /config/database.sqlite

metadataProviders:
  malClientId: "${SECRET_KOMF_MAL_CLIENT_ID}"
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: "MANGA"
      authorRoles: ["WRITER"]
      artistRoles: ["PENCILLER", "INKER", "COLORIST", "LETTERER", "COVER"]
    mal:
      priority: 20
      enabled: true
      mediaType: "MANGA"
    mangaDex:
      priority: 90
      enabled: false
