---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  chartRef:
    kind: OCIRepository
    name: csi-driver-nfs
  interval: 1h
  values:
    controller:
      enableSnapshotter: false
    storageClass:
      create: true
      name: nfs-rwx
      mountOptions:
        - nfsvers=4.1
        - hard
        - noatime
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        server: titan.internal
        share: /volume/831ea94d-16c9-4e58-8e74-e118a46b0aa9/.srv/.unifi-drive/homeops/.data
        subDir: kubernetes/${pvc.metadata.namespace}/${pvc.metadata.name}
        csi.storage.k8s.io/provisioner-secret-name: nfs-mount-secret
        csi.storage.k8s.io/provisioner-secret-namespace: kube-system
