---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 1h
  values:
    controllers:
      jellyfin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          jellyfin:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.6@sha256:25db4eb10143c1c12adb79ed978e31d94fc98dc499fbae2d38b2c935089ced3e
            env:
              TZ: America/New_York
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_PublishedServerUrl: https://jellyfin.beholdenkey.dev
              NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
            ports:
              - containerPort: 8096
                name: http
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
              limits:
                nvidia.com/gpu: 1
          vue:
            image:
              repository: ghcr.io/jellyfin/jellyfin-vue
              tag: unstable.2025-05-15.f3ced5d
            env:
              DEFAULT_SERVERS: localhost:8096
              DISABLE_SERVER_SELECTION: "true"
              TZ: America/New_York
            ports:
              - containerPort: 80
                name: http
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: http
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
        pod:
          runtimeClassName: nvidia
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 4000
    service:
      jellyfin:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.40.180
        externalTrafficPolicy: Local
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: *port
          vue:
            port: 80

    route:
      jellyfin:
        hostnames:
          - "{{ .Release.Name }}.beholdenkey.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: jellyfin
                port: 8096
      vue:
        hostnames:
          - "jellyvue.beholdenkey.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: jellyfin
                port: 80
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      metadata:
        size: 10Gi
        accessMode: ReadWriteOnce
        suffix: "metadata"
        globalMounts:
          - path: /metadata
            subPath: metadata
          - path: /config/data/introskipper
            subPath: introskipper
      tmpfs:
        type: emptyDir
        advancedMounts:
          jellyfin:
            app:
              - path: /cache
                subPath: cache
              - path: /tmp
                subPath: tmp
              - path: /transcode
                subPath: transcode
      media:
        type: nfs
        server: titan.internal
        path: /var/nfs/shared/media
        globalMounts:
          - path: /media
            readOnly: false

