---
# yaml-language-server: $schema=https://schemas.zinn.ca/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grimmory
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grimmory-secret
    creationPolicy: Owner
    template:
      data:
        grimmory_mariadb_password: "{{ .MARIADB_PASSWORD }}"
        grimmory_mariadb_root_password: "{{ .MARIADB_ROOT_PASSWORD }}"
  dataFrom:
    - extract:
        key: grimmory
