---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grimmory
spec:
  chartRef:
    kind: OCIRepository
    name: grimmory
  interval: 1h
  values:
    controllers:
      grimmory:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          mariadb:
            image:
              repository: docker.io/library/mariadb
              tag: 12.2.2-noble
            env:
              MARIADB_DATABASE: grimmory
              MARIADB_PASSWORD: "grimmory"
              MARIADB_ROOT_PASSWORD: "root"
              MARIADB_USER: grimmory
              PGID: "1000"
              PUID: "1000"
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - mariadb-admin
                      - ping
                      - --socket=/run/mysqld/mysqld.sock
                      - --user=root
                      - --password=root
            restartPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
              seccompProfile:
                type: Unconfined
        containers:
          grimmory:
            image:
              repository: ghcr.io/grimmory-tools/grimmory
              tag: v2.3.0@sha256:9014247f591074529894f81115ca40f899db697e89f72c2fe91ec530e3f19597
            env:
              BOOKLORE_PORT: &port 6060
              DATABASE_PASSWORD: grimmory
              DATABASE_URL: jdbc:mariadb://localhost:3306/grimmory
              DATABASE_USERNAME: grimmory
              TZ: America/New_York
            probes:
              liveness: &appProbe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: *port
              readiness: *appProbe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: *port
                  failureThreshold: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
    route:
      grimmory:
        hostnames:
          - "{{ .Release.Name }}.beholdenkey.dev"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      grimmory:
        controller: grimmory
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          grimmory:
            grimmory:
              - path: /app/data
                subPath: app
            mariadb:
              - path: /var/lib/mysql
                subPath: mysql
      media:
        type: nfs
        server: titan.internal
        path: /var/nfs/shared/media
        advancedMounts:
          grimmory:
            grimmory:
              - path: /books
                subPath: library/books
              - path: /bookdrop
                subPath: library/ingest

      mysqld:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Mi
        advancedMounts:
          grimmory:
            mariadb:
              - path: /run/mysqld
      tmp:
        type: emptyDir
        medium: Memory
        sizeLimit: 100Mi
        advancedMounts:
          grimmory:
            grimmory:
              - path: /tmp
            mariadb:
              - path: /tmp

