---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kueue
spec:
  chartRef:
    kind: OCIRepository
    name: kueue
  interval: 1h
  values:
    enablePrometheus: true
    # -- Enable x509 automated certificate management using cert-manager (cert-manager.io)
    enableCertManager: true
    # -- Enable API Priority and Fairness configuration for the visibility API
    enableVisibilityAPF: false
    # -- Enable KueueViz dashboard
    enableKueueViz: false
    controllerManager:
      # -- ControllerManager's feature gates
      featureGates: []
      #  - name: PartialAdmission
      #    enabled: true
      manager:
        # -- ControllerManager's pod priorityClassName
        priorityClassName:
        image:
          # -- ControllerManager's image repository
          repository: us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue
          # -- ControllerManager's image tag
          tag: v0.16.2@sha256:3a03b59b3165fc71bc174960976a6bdd3962d797dc2f295ab0c438f55f60cce7
          # -- ControllerManager's image pullPolicy.
          # This should be set to 'IfNotPresent' for released version
          pullPolicy: Always
        podAnnotations: {}
        # -- ControllerManager's pod resources
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
        # -- ControllerManager's pod securityContext
        podSecurityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        # -- ControllerManager's container securityContext
        containerSecurityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      # -- ControllerManager's replicas count
      replicas: 1
      # -- ControllerManager's imagePullSecrets
      imagePullSecrets: []
      readinessProbe:
        # -- ControllerManager's readinessProbe initialDelaySeconds
        initialDelaySeconds: 5
        # -- ControllerManager's readinessProbe periodSeconds
        periodSeconds: 10
        # -- ControllerManager's readinessProbe timeoutSeconds
        timeoutSeconds: 1
        # -- ControllerManager's readinessProbe failureThreshold
        failureThreshold: 3
        # -- ControllerManager's readinessProbe successThreshold
        successThreshold: 1
      livenessProbe:
        # -- ControllerManager's livenessProbe initialDelaySeconds
        initialDelaySeconds: 15
        # -- ControllerManager's livenessProbe periodSeconds
        periodSeconds: 20
        # -- ControllerManager's livenessProbe timeoutSeconds
        timeoutSeconds: 1
        # -- ControllerManager's livenessProbe failureThreshold
        failureThreshold: 3
        # -- ControllerManager's livenessProbe successThreshold
        successThreshold: 1
      # -- ControllerManager's nodeSelector
      nodeSelector: {}
      # -- ControllerManager's tolerations
      tolerations: []
      # -- ControllerManager's topologySpreadConstraints
      topologySpreadConstraints: []
      podDisruptionBudget:
        # -- Enable PodDisruptionBudget
        enabled: false
        # -- PodDisruptionBudget's topologySpreadConstraints
        minAvailable: 1
    managerConfig:
      # -- controller_manager_config.yaml.
      # ControllerManager utilizes this yaml via manager-config Configmap.
      # @default -- controllerManagerConfigYaml
      controllerManagerConfigYaml: |-
        apiVersion: config.kueue.x-k8s.io/v1beta2
        kind: Configuration
        health:
          healthProbeBindAddress: :8081
        metrics:
          bindAddress: :8443
        # enableClusterQueueResources: true
        webhook:
          port: 9443
        leaderElection:
          leaderElect: true
          resourceName: c1f6bfd2.kueue.x-k8s.io
        controller:
          groupKindConcurrency:
            Job.batch: 5
            Pod: 5
            Workload.kueue.x-k8s.io: 5
            LocalQueue.kueue.x-k8s.io: 1
            ClusterQueue.kueue.x-k8s.io: 1
            ResourceFlavor.kueue.x-k8s.io: 1
        clientConnection:
          qps: 50
          burst: 100
        integrations:
          frameworks:
          - "batch/job"
          - "jobset.x-k8s.io/jobset"
          - "pod"
          - "deployment"
          - "statefulset"
          - "leaderworkerset.x-k8s.io/leaderworkerset"
    metrics:
      prometheusNamespace: observability
