---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-smb-media
spec:
  capacity:
    storage: 48Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - guest
    - vers=3.0
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: 192.168.1.10/media
    volumeAttributes:
      source: "//192.168.1.10/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-smb-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: unifi-smb-media
  resources:
    requests:
      storage: 48Ti
