---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-smb-media
spec:
  capacity:
    storage: 48Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3.1.1
    - mfsymlinks
    - noperm
    - noserverino
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: titan.internal/media
    volumeAttributes:
      source: "//titan.internal/media"
    nodeStageSecretRef:
      name: unifi-smb-media-secret
      namespace: media
