---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-smb-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: unifi-smb-media
  resources:
    requests:
      storage: 48Ti
