---
version: v1alpha1
debug: false
persist: true
machine:
  type: worker
  token: 711vez.bhn62qv018hv92f4
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEEva2NzMXI3VWFiQ1dqTHhiMlRIVVhNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5qQXhNRFV3TVRVeU5UZGFGdzB6TmpBeE1ETXdNVFV5TlRkYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBOWNyUm00YVU0OHdkTkhKNWFmbi9KdTMwaElFcVlkUm9yUmMwCnJuMW93dUNqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVV05Fd0ZkTE9TOTh0ZzdzUgpkdWhGUnU3aytMQXdCUVlESzJWd0EwRUFGRTNOUlBIby9TNjRYNisxYmxHZjd6VGd4ejJnRnJmV1pFZVJxalRCCkR1Tlg5WWd3dEtjbjEyS3JhanNRanlYWEczNnhzYm53K29yaC95aXU1Y2pnQ3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: ""
  certSANs:
    - 127.0.0.1
    - 192.168.40.20
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.35.0
    extraConfig:
      serializeImagePulls: false
    defaultRuntimeSeccompProfileEnabled: true
    nodeIP:
      validSubnets:
        - 192.168.40.0/24
    disableManifestsDirectory: true
  network:
    interfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:b4:88:c3
        addresses:
          - 192.168.40.25/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.40.1
        mtu: 1500
        dhcp: false
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    disableSearchDomain: true
  install:
    disk: /dev/vda
    image: factory.talos.dev/installer/30191123127e198e4f26041bf408a085944ead862a1ff09a620ee59f2981c3a9:v1.12.0
    wipe: false
    grubUseUKICmdline: true
  files:
    - content: |-
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          device_ownership_from_security_context = true
      permissions: 0o0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  time:
    disabled: false
    servers:
      - 162.159.200.1
      - 162.159.200.123
  sysctls:
    fs.inotify.max_user_instances: "8192"
    fs.inotify.max_user_watches: "1048576"
    net.core.default_qdisc: fq
    net.core.rmem_max: "7500000"
    net.core.wmem_max: "7500000"
    net.ipv4.neigh.default.gc_thresh1: "4096"
    net.ipv4.neigh.default.gc_thresh2: "8192"
    net.ipv4.neigh.default.gc_thresh3: "16384"
    net.ipv4.tcp_congestion_control: bbr
    net.ipv4.tcp_fastopen: "3"
    net.ipv4.tcp_mtu_probing: "1"
    net.ipv4.tcp_rmem: 4096 87380 33554432
    net.ipv4.tcp_slow_start_after_idle: "0"
    net.ipv4.tcp_window_scaling: "1"
    net.ipv4.tcp_wmem: 4096 65536 33554432
    sunrpc.tcp_max_slot_table_entries: "128"
    sunrpc.tcp_slot_table_entries: "128"
    user.max_user_namespaces: "11255"
    vm.nr_hugepages: "1024"
  features:
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: true
  nodeLabels:
    intel.feature.node.kubernetes.io/gpu: "true"
cluster:
  id: o7DygUV_cFRgm4NzKPsRoDC57-7RySF3IWvwWwG7FS0=
  secret: tI58UnI6U5rMhGwVFr+U0TOm2ufl8zAfD4xVSco9n3E=
  controlPlane:
    endpoint: https://192.168.40.20:6443
  clusterName: kubernetes
  network:
    cni:
      name: none
    dnsDomain: cluster.local
    podSubnets:
      - 10.42.0.0/16
    serviceSubnets:
      - 10.43.0.0/16
  token: 79sat6.jiisokgs6tfet5kf
  ca:
    crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQVBGb09Xc1pHTy9VNGM1eTdWWk9wcm93Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOakF4TURVd01UVXlOVFphRncwek5qQXhNRE13TVRVeQpOVFphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVRGTnBQb1NtUmY2YjJoWWhRYkIrNjVHYTJhbkc3bmloWVBESjFtYVRGWjFDb1BLVHUrZUJzZTQrMDMKVFhTN1hONTd5a0pFWm5PSW5ZWVlUTmlNeEFtZG8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGR2Q5Z2NBNTVCVlp5YSt5L2tDbXVXVExWeE9BTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUFYdWp3bzAKSHJSWWtSNTJiRXpVU2JnU3RFVHRzZm1oV2RvRUNLQjh5b2ptQWlFQTI5c1UwQ0Fkc3RiQXZOOUZlRlpIWWQrTAo2L2R6UjJZWnlWUzFDczZIRnhVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    key: ""
  discovery:
    enabled: true
    registries:
      kubernetes:
        disabled: true
      service: {}
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: "off"
hostname: homeops-worker-01
---
apiVersion: v1alpha1
kind: VLANConfig
name: ens18.90
vlanID: 90
parent: ens18
up: true
mtu: 1500
