use_default_settings: true

server:
  limiter: true
  image_proxy: true
  method: GET
  public_instance: false

search:
  autocomplete: duckduckgo
  favicon_resolver: duckduckgo
  languages:
    - all
    - en
    - en-US
  formats:
    - html
    - json

general:
  instance_name: LDS Search

ui:
  default_theme: simple
  infinite_scroll: true
  query_in_title: true
  results_on_new_tab: true
  static_use_hash: true
  theme_args:
    simple_style: auto

categories_as_tabs:
  general:
  news:
  images:
  videos:
  map:

enabled_plugins:
  - Basic Calculator
  - Hash plugin
  - Open Access DOI rewrite
  - Self Informations
  - Tracker URL remover
  - Unit converter plugin

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    categories: [general, web]
    paging: true

  - name: duckduckgo news
    engine: duckduckgo_extra
    shortcut: ddn
    categories: [news]
    paging: true
    time_range_support: true

  - name: brave
    engine: brave
    shortcut: br
    categories: [general, web]
    brave_category: search
    paging: true
    time_range_support: true

  - name: brave.news
    engine: brave
    shortcut: brnews
    categories: [news]
    brave_category: news
    paging: true
    time_range_support: true

  - name: bing news
    engine: bing_news
    shortcut: bin
    categories: [news]
    paging: true
    time_range_support: true

  - name: google news
    engine: google_news
    shortcut: gon
    categories: [news]
    paging: true
    time_range_support: true

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    categories: [general]

  - name: wikidata
    engine: wikidata
    shortcut: wd
    categories: [general]

  - name: openstreetmap
    engine: openstreetmap
    shortcut: osm
    categories: [map]

  - name: photon
    engine: photon
    shortcut: ph
    categories: [map]

  - name: github
    engine: github
    shortcut: gh
    categories: [general]

  - name: reddit
    engine: reddit
    shortcut: re
    categories: [general]
