---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi-operator
spec:
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: cephconnections.csi.ceph.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: clientprofiles.csi.ceph.io
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: drivers.csi.ceph.io
    - apiVersion: apps/v1
      kind: Deployment
      name: ceph-csi-operator-controller-manager
      namespace: ceph-csi-operator-system
  interval: 1h
  path: ./kubernetes/apps/ceph-csi-operator-system/ceph-csi-operator/operator
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ceph-csi-operator-system
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-csi-drivers
spec:
  dependsOn:
    - name: ceph-csi-operator
  interval: 1h
  path: ./kubernetes/apps/ceph-csi-operator-system/ceph-csi-operator/drivers
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: ceph-csi-operator-system
